### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by petewest-vocovo**
### This Pull Request is associated with card(s) URL(s):

n/a

### Brief summary of the problem/need for this work:

This package is quite out of date, with very old dependencies, and requires quite a lot of work to integrate with projects.

### Detail of how this Pull Request solves the problem/need:

- Removes yarn, which we don't use anymore
- Moves relevant packages out of dev dependencies, so these don't need to be installed separately in each project
- Adds `eslint` and `prettier` as peer dependencies so these are checked when installing this
- Updates packages to latest versions
- Adds basic CI and dependabot

### Notes to reviewers:

- There are some minor changes which I've not listed, feel free to read the commits for more detail
- This removes the react packages, since they are not applicable for most projects
- Using version 2.0.0 will require updating `eslint` and `prettier` to the latest versions

### CODE REVIEW

**Review by davecranwell-vocovo — APPROVED** [review]
Nice one!

**Review by pavtaras-vocovo — COMMENTED** [review]
Looks good, do you have plans to migrate package to `npm` registry? Or in separate PR? Also have you tested it with any of existing repos?

**Review by Strongbyte-CM — APPROVED** [review]

**Comment by petewest-vocovo** [comment]
@pavtaras-vocovo This package is already published on NPM:
https://www.npmjs.com/package/@vocovo/eslint-config-vocovo

So far I've tested it with VocoApps, I will also test on vortal-server.

I will also post notes for other teams to update this.

**Comment by petewest-vocovo** [comment]
@pavtaras-vocovo have tested on the Vortal now and it all works.
Also have added docs for using an auth token.

**Review by pavtaras-vocovo — APPROVED** [review]

**Pull request merged**
